---
- hosts: all
  become: true
  vars_files:
    - ../vars.yaml
  tasks:
    - name: Install docker
      yum:
        state: latest
        pkg:
          - docker
    - name: Install docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/{{compose.release}}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}
        dest: "{{compose.binary}}"
        mode: "0755"
        owner: root
        group: root
    - name: Copy compose service file
      template:
        src: ../templates/docker-compose@.service.j2
        dest: /etc/systemd/system/docker-compose@.service
        owner: root
        group: root
        mode: "0644"
    - name: Start docker service
      systemd:
        daemon_reload: yes
        name: docker
        state: started
        enabled: yes
